"""Models and schemas for ARKA Validation Agent.

The Validation Agent independently checks high-confidence / high-severity findings
(e.g. from Nuclei) to distinguish confirmed vulnerabilities from false positives.
"""

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field

from arka.app.core.assets.models import utc_now


class FindingValidationStatus(str, Enum):
    """Validation lifecycle states for security findings."""

    OBSERVED = "observed"
    SUSPECTED = "suspected"
    VALIDATING = "validating"
    VALIDATED = "validated"
    FALSE_POSITIVE = "false_positive"


class ValidationAction(BaseModel):
    """An action proposed by the Validation Agent to verify a candidate finding."""

    tool_name: str
    target: str
    arguments: dict[str, Any] = Field(default_factory=dict)
    rationale: str = ""


class ValidationPlan(BaseModel):
    """Structured verification plan generated by the Validation Agent."""

    finding_id: str
    reasoning: str
    actions: list[ValidationAction] = Field(default_factory=list)


class ValidationAssessment(BaseModel):
    """Structured assessment produced by analyzing verification results."""

    finding_id: str
    status: FindingValidationStatus
    confidence: float = Field(ge=0.0, le=1.0)
    reasoning: str
    evidence_refs: list[str] = Field(default_factory=list)
    timestamp: str = Field(default_factory=lambda: utc_now().isoformat())


class ValidationState(BaseModel):
    """State tracking for a Validation Agent verification workflow."""

    engagement_id: str
    finding_id: str
    status: FindingValidationStatus = FindingValidationStatus.OBSERVED
    iterations: int = 0
    max_iterations: int = 3
    plan: ValidationPlan | None = None
    assessment: ValidationAssessment | None = None
    evidence_refs: list[str] = Field(default_factory=list)
    completed: bool = False
