"""Nmap domain models and safe argument construction for ARKA Phase 2.2.1.

All models are Pydantic v2 BaseModels. NmapScanConfig enforces an explicit
argument allowlist — only typed fields can appear in the generated argv.
The LLM has zero access to raw Nmap CLI flags.
"""

from __future__ import annotations

import re
from typing import Any

from pydantic import BaseModel, Field, field_validator

# Strict regex for port specifications: digits, commas, hyphens only.
_PORT_PATTERN = re.compile(r"^[0-9]+([,\-][0-9]+)*$")


class NmapScanConfig(BaseModel):
    """Safe, strongly-typed Nmap scan configuration.

    Exposes ONLY the explicitly allowed scan parameters. No raw flag
    passthrough. The LLM sees typed fields, never CLI flags.

    Allowed flags (generated by to_argv):
        -sV  (service detection)
        -sC  (default scripts — escalates risk to HIGH)
        -p   (port specification)
        -T   (timing template — ≥3 escalates risk to HIGH)
        -oX - (XML output to stdout, hardcoded)
    """

    ports: str | None = Field(
        default=None,
        description="Port specification (e.g. '80,443' or '1-1024'). "
        "Only digits, commas, and hyphens allowed.",
    )
    service_detection: bool = Field(
        default=True,
        description="Enable service/version detection (-sV).",
    )
    default_scripts: bool = Field(
        default=False,
        description="Enable default NSE scripts (-sC). "
        "Escalates risk to HIGH, requiring human approval.",
    )
    timing_template: int = Field(
        default=2,
        ge=0,
        le=4,
        description="Timing template 0-4 (-T0 to -T4). Values ≥3 escalate risk to HIGH.",
    )

    @field_validator("ports")
    @classmethod
    def validate_ports(cls, v: str | None) -> str | None:
        """Validate port specification contains only safe characters."""
        if v is None:
            return v
        v = v.strip()
        if not v:
            return None
        if not _PORT_PATTERN.match(v):
            raise ValueError(
                f"Invalid port specification: '{v}'. Only digits, commas, and hyphens are allowed."
            )
        return v

    def requires_escalation(self) -> bool:
        """Check if this configuration requires risk escalation to HIGH.

        Returns True when the scan includes aggressive or intrusive options:
        - default_scripts=True (-sC can probe services intrusively)
        - timing_template >= 3 (aggressive timing increases detection risk)
        """
        return self.default_scripts or self.timing_template >= 3

    def to_argv(self, target: str) -> list[str]:
        """Construct a safe Nmap argument array from typed fields only.

        The target comes from the authoritative ToolRequest, NOT from
        LLM-proposed arguments. Only explicitly allowed flags appear.

        Args:
            target: Authorized target from ToolRequest.target.

        Returns:
            List of string arguments suitable for subprocess execution.
        """
        argv: list[str] = ["nmap"]

        # Service detection
        if self.service_detection:
            argv.append("-sV")

        # Default scripts (escalation-triggering)
        if self.default_scripts:
            argv.append("-sC")

        # Port specification
        if self.ports:
            argv.extend(["-p", self.ports])

        # Timing template
        argv.append(f"-T{self.timing_template}")

        # XML output to stdout (hardcoded, not LLM-controllable)
        argv.extend(["-oX", "-"])

        # Target (from authoritative ToolRequest, never from LLM arguments)
        argv.append(target)

        return argv


class NmapService(BaseModel):
    """Parsed Nmap service detection result."""

    name: str = ""
    product: str = ""
    version: str = ""
    extra_info: str = ""
    cpe: list[str] = Field(default_factory=list)


class NmapScript(BaseModel):
    """Parsed Nmap NSE script output."""

    script_id: str
    output: str = ""


class NmapPort(BaseModel):
    """Parsed Nmap port result with optional service and script data."""

    port: int
    protocol: str = "tcp"
    state: str = "unknown"
    service: NmapService | None = None
    scripts: list[NmapScript] = Field(default_factory=list)


class NmapHost(BaseModel):
    """Parsed Nmap host result."""

    address: str
    address_type: str = "ipv4"
    hostnames: list[str] = Field(default_factory=list)
    status: str = "unknown"
    ports: list[NmapPort] = Field(default_factory=list)


class NmapResult(BaseModel):
    """Structured result from parsing Nmap XML output.

    This is an intermediate representation. Phase 2.2.2 will normalize
    it into the ARKA asset database model.
    """

    success: bool = True
    error: str | None = None
    scan_metadata: dict[str, Any] = Field(default_factory=dict)
    hosts: list[NmapHost] = Field(default_factory=list)
    raw_xml: str = ""
